# Generated by Django 5.0.4 on 2024-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.CharField(blank='True', max_length=150, null='True', verbose_name='URL')),
                ('content', models.TextField(blank='True', null='True', verbose_name='Содержимое')),
                ('preview', models.ImageField(blank='True', null='True', upload_to='media/photo')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
