# Generated by Django 5.0.4 on 2024-05-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование категории', max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(blank='True', help_text='Введите описание категории', null='True', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, blank='True', null='True', verbose_name='Дата создания')),
                ('name', models.CharField(help_text='Введите наименование продукта', max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(blank='True', help_text='Введите описание продукта', null='True', verbose_name='Описание')),
                ('image', models.ImageField(blank='True', help_text='Загрузите фото продукта', null='True', upload_to='media/photo')),
                ('price', models.IntegerField(blank='True', help_text='Введите цену продукта', null='True', verbose_name='Цена')),
                ('updated_at', models.DateField(auto_now_add=True, null='True', verbose_name='Дата изменения')),
                ('category', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category', 'name'],
            },
        ),
    ]
