# Generated by Django 5.0.4 on 2024-05-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank='True', help_text='Загрузите фото продукта', null='True', upload_to='products/photo'),
        ),
    ]
